# Generated by Django 4.1.7 on 2023-03-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="None")),
                ("parent_category", models.IntegerField()),
                ("path", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("status", models.BooleanField()),
                ("deleted", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=50)),
                ("contact_number", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("id_number", models.IntegerField()),
                ("role", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("profile", models.CharField(max_length=50)),
                ("status", models.BooleanField()),
                ("deleted", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_parent_id", models.IntegerField()),
                ("client_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("dateTime_from", models.DateTimeField()),
                ("dateTime_to", models.DateTimeField()),
                ("sub_events", models.ImageField(upload_to="")),
                ("has_tickets", models.BooleanField()),
                ("total_count", models.IntegerField()),
                ("total_cost", models.IntegerField()),
                ("total_price", models.IntegerField()),
                ("event_grand_total", models.IntegerField()),
                ("paid_amount", models.IntegerField()),
                ("pending_amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "event_location_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("event_id", models.IntegerField()),
                ("title", models.CharField(max_length=50)),
                ("street_detail", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("zipcode", models.IntegerField()),
                ("location_link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EventTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_number", models.IntegerField()),
                ("payment_method", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
                ("created_date", models.DateTimeField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_management_application.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_note", models.CharField(max_length=50)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_management_application.employee",
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_management_application.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catgory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_management_application.category",
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_management_application.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event_management_application.eventlocation",
            ),
        ),
    ]
