# Generated by Django 4.2.6 on 2023-10-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='remain_tickets',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_COMPANY_ADDRESS',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_COMPANY_EMAIL',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_COMPANY_LANDLINE',
            field=models.CharField(default='000', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_COMPANY_PHONE',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_COMPANY_TITLE',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_DATABASE_PASSWORD',
            field=models.CharField(default='pass', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_DATABASE_USER',
            field=models.CharField(default='database name', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_EMAIL_HOST_PASSWORD',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_EMAIL_HOST_USER',
            field=models.CharField(default='Jash', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_PAYMENT_METHOD',
            field=models.CharField(choices=[('RAZORPAY', 'RAZORPAY'), ('PAYTM', 'PAYTM'), ('PAYPAL', 'PAYPAL'), ('CASH', 'CASH')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_RAZOR_KEY_ID',
            field=models.CharField(default='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfigs',
            name='system_config_RAZOR_KEY_SECRET',
            field=models.CharField(default='key', max_length=50),
        ),
    ]
