# Generated by Django 4.1.7 on 2023-03-16 04:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("event_management_application", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="status",),
        migrations.RemoveField(model_name="client", name="created_date",),
        migrations.RemoveField(model_name="client", name="updated_date",),
        migrations.RemoveField(model_name="employee", name="created_date",),
        migrations.RemoveField(model_name="employee", name="status",),
        migrations.RemoveField(model_name="employee", name="updated_date",),
        migrations.RemoveField(model_name="eventtransaction", name="created_date",),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Active"), (0, "Inactive")],
                default=1,
                help_text="1->Active, 0->Inactive",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_on",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Active"), (0, "Inactive")],
                default=1,
                help_text="1->Active, 0->Inactive",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_on",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_on",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="eventtransaction",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="eventtransaction",
            name="updated_on",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_number",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(10)]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_number",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(10)]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.IntegerField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinValueValidator(6)],
            ),
        ),
    ]
