# Generated by Django 4.2 on 2023-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management_application", "0002_order_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="remain_tickets",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
