# Generated by Django 4.2.6 on 2023-10-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_application', '0002_event_is_deleted_event_remain_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_id',
        ),
    ]
