# Generated by Django 4.1.7 on 2023-03-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event_management_application",
            "0002_remove_category_status_remove_client_created_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtransaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("Online", "Online"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
