# Generated by Django 4.1.7 on 2023-03-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management_application", "0003_alter_eventtransaction_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="deleted",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "yes"), (0, "No")],
                default=0,
                help_text="1->yes, 0->No",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="deleted",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "yes"), (0, "No")],
                default=0,
                help_text="1->yes, 0->No",
                null=True,
            ),
        ),
    ]
