# Generated by Django 4.2 on 2023-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management_application", "0003_event_remain_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
