# Generated by Django 4.1.7 on 2023-03-17 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event_management_application",
            "0004_alter_category_deleted_alter_employee_deleted",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlocation",
            name="event_location_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="eventlocation",
            name="zipcode",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(6)]
            ),
        ),
    ]
